<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- This is an example of a URDF. -->
    <!-- As we move through the file, new things to note will be pointed out. -->
    <!-- It's not meant an example of GOOD design, but an example of some of the various features of URDF/xacro. -->



    <!-- This will include all the contents of example_include.xacro first. Go check it out! -->
    <xacro:include filename="example_include.xacro" />

    <xacro:property name="arm_1_length" value="1" />
    <xacro:property name="arm_1_radius" value="0.1" />

    <xacro:property name="arm_2_length" value="0.7" />
    <xacro:property name="arm_2_radius" value="0.1" />

    <xacro:property name="arm_3_length" value="0.5" />
    <xacro:property name="arm_3_radius" value="0.1" />

    <xacro:property name="effector_length" value="0.2" />
    <xacro:property name="effector_radius" value="0.03" />

    <!-- This first link called "world" is empty -->
    <link name="world"></link>


    <!-- A simple fixed joint from our empty world link, to our base. -->
    <!-- The base origin is offset from the world origin. -->
    <joint name="base_joint" type="fixed">
        <origin xyz="0.5 0.0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>        
    </joint>


    <!-- base_link is a large rectangular plate. Some things to note: -->
    <!-- - We set the visual origin Z to half the box height, so that the link origin sits at the bottom of the box -->
    <!-- - We set the collision to be identical to the visual -->
    <!-- - We specified the colour manually (but still need to enter a name) -->
    <!-- - We specified all the inertial parameters manually -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
                <box size="1.0 0.7 0.1" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
                <box size="1.0 0.7 0.1" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial>
    </link>

    <joint name="arm_1_joint" type="revolute">
        <origin xyz="0.25 0 0.10" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="arm_1_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="${pi}" velocity="100" effort="100"/> 
    </joint>


    <!-- arm_link describes the arm -->
    <!-- - We use the "property" feature to define the arm length and radius and use them multiple times -->
    <!-- - The visual/collision origin is set to halfway along the length (similar to the box), but also with a rotation (again using the mathematical features). -->
    <!--   This is because the cylinder extends along the Z axis by default, but we want it to be along the X axis (when the joint is at 0) -->

    <link name="arm_1_link">
        <visual>
            <origin xyz="0 0 ${arm_1_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_1_length}" radius="${arm_1_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${arm_1_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${arm_1_length}" radius="${arm_1_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_1_length}" radius="${arm_1_radius}">
            <origin xyz="0 0 ${arm_1_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="arm_2_joint" type="revolute">
        <origin xyz="0.0 0 ${arm_1_length}" rpy="${pi/2} 0 0"/>
        <parent link="arm_1_link"/>
        <child link="arm_2_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/4}" upper="${pi/4}" velocity="100" effort="100"/> 
    </joint>

    <link name="arm_2_link">
        <visual>
            <origin xyz="${arm_2_length/2} 0 0" rpy="0 ${-pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_2_length}" radius="${arm_2_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_2_length/2} 0 0" rpy="0 ${-pi/2} 0"/>
            <geometry>
                <cylinder length="${arm_2_length}" radius="${arm_2_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_2_length}" radius="${arm_2_radius}">
            <origin xyz="${arm_2_length/2} 0 0" rpy="0 ${-pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="arm_3_joint" type="revolute">
        <origin xyz="${arm_2_length} 0 0" rpy="0 ${pi/2} 0"/>
        <parent link="arm_2_link"/>
        <child link="arm_3_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <link name="arm_3_link">
        <visual>
            <origin xyz="0 -${arm_3_length/2} 0" rpy="${pi/2} 0 0"/>
            <geometry>                
                <cylinder length="${arm_3_length}" radius="${arm_3_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 -${arm_3_length/2} 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder length="${arm_3_length}" radius="${arm_3_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_3_length}" radius="${arm_3_radius}">
            <origin xyz="0 -${arm_3_length/2} 0" rpy="${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="effector_joint" type="fixed">
        <origin xyz="0 ${-arm_3_length-effector_length} 0" rpy="${pi/2} 0 0"/>
        <parent link="arm_3_link"/>
        <child link="effector_link"/>
    </joint>

    <link name="effector_link">
    <visual>
            <origin xyz="0 0 ${-effector_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${effector_length}" radius="${effector_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0 ${-effector_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${effector_length}" radius="${effector_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_3_length}" radius="${arm_3_radius}">
            <origin xyz="0 0 ${-effector_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


</robot>
